// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/base/Button.vue')['default']
    Footer: typeof import('./components/footer/index.vue')['default']
    Hero: typeof import('./components/hero/index.vue')['default']
    HeroBtn: typeof import('./components/hero/heroBtn/index.vue')['default']
    HeroSticky: typeof import('./components/hero/heroSticky/index.vue')['default']
    HeroSubhead: typeof import('./components/hero/heroSubhead/index.vue')['default']
    'HeroSubhead.vue': typeof import('./components/hero/heroSubhead.vue/index.vue')['default']
    IconCircleVerified: typeof import('./components/icons/IconCircleVerified.vue')['default']
    IconInlineTeam: typeof import('./components/icons/IconInlineTeam.vue')['default']
    IconTeam: typeof import('./components/icons/IconTeam.vue')['default']
    IconTeamIcon: typeof import('./components/icons/IconTeam.vue')['default']
    Navbar: typeof import('./components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VSpacer: typeof import('./components/base/VSpacer.vue')['default']
  }
}
